services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  dotnet_publisher:
    build:
      context: ./
      dockerfile: dotnet_publisher/Dockerfile
    depends_on:
      - rabbitmq

  dotnet_consumer:
    build:
      context: ./
      dockerfile: dotnet_consumer/Dockerfile
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: